### PR TITLE
Fix exit with parent on macOS

### LINKED ISSUE #29: Fix exit with parent on macOS
It should be possible to do an [equivalent, although much trickier](https://gitlab.com/nbdkit/nbdkit/-/blob/master/common/utils/exit-with-parent.c#L84-159), variation of [what we currently do for Linux](https://github.com/appsignal/appsignal-wrap/blob/main/src/exit.rs) in macOS.

### PR DESCRIPTION
**Pull request by unflxw**
Implement exit with parent functionality for macOS, by porting the reference implementation in `nbdkit` to Rust.

Fixes #29.

### CODE REVIEW

File: src/exit.rs [hunk 1]
```diff
@@ -18,9 +18,100 @@ fn set_exit_with_parent() {
...
+    // Because this runs in `pre_exec` (after fork, before exec), any thread we spawn
+    // would be killed by the subsequent `exec` call. Instead, we double-fork a detached
+    // watcher process: the intermediate process exits immediately (so the watcher is
+    // re-parented to PID 1), and the watcher blocks on `kevent` until either the parent
+    // or the child exits.
+    use libc::{c_int, close, fork, getpid, getppid, kevent, kqueue, pid_t, waitpid};
+    use libc::{EVFILT_PROC, EV_ADD, EV_ENABLE, NOTE_EXIT, SIGTERM};
+    use std::mem;
+
+    unsafe {
```
Comment (tombruijn) [inline src/exit.rs]: In the PR description you said you ported this. What is the original source? Could you link that in the code comments?

**Review by tombruijn — APPROVED** [review]
